version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    # networks:
    #   - openbanking_forgerock
    ports:
      - 6379:6379

  mongo:
    image: mongo:3.6-jessie
    container_name: mongo
    hostname: mongo
    # networks:
    #   - openbanking_forgerock
    ports:
      - 27017:27017
# networks:
#   openbanking_forgerock:
