SSID: <some_software_statement_id>
ORGANISATION_ID: <some_organisation_id>
SSA: <some_software_statement_header>.<some_software_statement_payload>.<some_software_statement_signature>
KID: <some_kid>
request_object_signing_alg: PS256
encryption_private: ./keys/encryption/encryption_private.key
encryption_public: ./keys/encryption/encryption_public.pem
signature_private: ./keys/signature/signature_private.key
signature_public: ./keys/signature/signature_public.pem
transport_private: ./keys/transport/transport_private.key
transport_public: ./keys/transport/transport_public.pem
