swagger: '2.0'
info:
  title: Real Time Event Notification API
  description: >
    Swagger for Real Time Event Notification API (TPP Endpoints)


    Note that the `EventNotification` is expected to be a signed JSON Web Token
    (JSON Web Signature) with the payload encoded as per
    `#/definitions/OBEventNotification2`
  termsOfService: 'https://www.openbanking.org.uk/terms'
  contact:
    name: Service Desk
    email: ServiceDesk@openbanking.org.uk
  license:
    name: open-licence
    url: 'https://www.openbanking.org.uk/open-licence'
  version: v3.1.2
basePath: /open-banking/v3.1
schemes:
  - https
paths:
  /event-notifications:
    post:
      summary: Send an event notification
      operationId: CreateEventNotification
      consumes:
        - application/jose
      tags:
        - Event Notification
      parameters:
        - $ref: '#/parameters/EventNotification'
        - $ref: '#/parameters/x-fapi-interaction-id'
      responses:
        '202':
          description: Accepted
parameters:
  EventNotification:
    in: body
    name: EventNotification
    description: >-
      JSON Web Signature with payload encoded as per
      `#/definitions/OBEventNotification2`
    required: true
    schema:
      type: string
  x-fapi-interaction-id:
    in: header
    name: x-fapi-interaction-id
    type: string
    required: false
    description: An RFC4122 UID used as a correlation id.
definitions:
  OBEventNotification2:
    description: The resource-update event.
    type: object
    properties:
      iss:
        description: Issuer.
        type: string
      iat:
        description: 'Issued At. '
        type: integer
        format: int32
        minimum: 0
      jti:
        description: JWT ID.
        type: string
        minLength: 1
        maxLength: 128
      aud:
        description: Audience.
        type: string
        minLength: 1
        maxLength: 128
      sub:
        description: Subject
        type: string
        format: uri
      txn:
        description: Transaction Identifier.
        type: string
        minLength: 1
        maxLength: 128
      toe:
        description: Time of Event.
        type: integer
        format: int32
        minimum: 0
      events:
        $ref: '#/definitions/OBEvent2'
    required:
      - iss
      - iat
      - jti
      - aud
      - sub
      - txn
      - toe
      - events
    additionalProperties: false
  OBEvent2:
    description: Events.
    type: object
    properties:
      'urn:uk:org:openbanking:events:resource-update':
        $ref: '#/definitions/OBEventResourceUpdate2'
      'urn:uk:org:openbanking:events:account-access-consent-linked-account-update':
        $ref: >-
          #/definitions/OBExternalEventAccountAccessConsentLinkedAccountUpdateReason1Code
      'urn:uk:org:openbanking:events:consent-authorization-revoked':
        $ref: '#/definitions/OBEventConsentAuthorizationRevoked1'
    additionalProperties: false
  OBEventResourceUpdate2:
    description: Resource-Update Event.
    type: object
    required:
      - subject
    properties:
      subject:
        type: object
        properties:
          subject_type:
            description: 'Subject type for the updated resource. '
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rid':
            description: Resource Id for the updated resource.
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rty':
            description: Resource Type for the updated resource.
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rlk':
            items:
              $ref: '#/definitions/OBEventLink1'
            type: array
            description: Resource links to other available versions of the resource.
            minItems: 1
        required:
          - subject_type
          - 'http://openbanking.org.uk/rid'
          - 'http://openbanking.org.uk/rty'
          - 'http://openbanking.org.uk/rlk'
    additionalProperties: false
  OBExternalEventAccountAccessConsentLinkedAccountUpdateReason1Code:
    description: >-
      An event that indicates an account linked to a consent has move in/out of
      scope of the consent.
    type: object
    required:
      - subject
    properties:
      reason:
        description: Reason for the Account Access Consent Linked Account Update event.
        type: string
        minLength: 1
        maxLength: 128
      subject:
        type: object
        properties:
          subject_type:
            description: 'Subject type for the updated resource. '
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rid':
            description: Resource Id for the updated resource.
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rty':
            description: Resource Type for the updated resource.
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rlk':
            items:
              $ref: '#/definitions/OBEventLink1'
            type: array
            description: Resource links to other available versions of the resource.
            minItems: 1
        required:
          - subject_type
          - 'http://openbanking.org.uk/rid'
          - 'http://openbanking.org.uk/rty'
          - 'http://openbanking.org.uk/rlk'
    additionalProperties: false
  OBEventConsentAuthorizationRevoked1:
    description: >-
      An event that indicates a consent resource has had its authorisation
      revoked.
    type: object
    required:
      - subject
    properties:
      reason:
        description: Reason for the Consent Authorization Revoked event.
        type: string
        minLength: 1
        maxLength: 128
      subject:
        type: object
        properties:
          subject_type:
            description: 'Subject type for the updated resource. '
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rid':
            description: Resource Id for the updated resource.
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rty':
            description: Resource Type for the updated resource.
            type: string
            minLength: 1
            maxLength: 128
          'http://openbanking.org.uk/rlk':
            items:
              $ref: '#/definitions/OBEventLink1'
            type: array
            description: Resource links to other available versions of the resource.
            minItems: 1
        required:
          - subject_type
          - 'http://openbanking.org.uk/rid'
          - 'http://openbanking.org.uk/rty'
          - 'http://openbanking.org.uk/rlk'
    additionalProperties: false
  OBEventLink1:
    description: Resource links to other available versions of the resource.
    type: object
    properties:
      version:
        description: Resource version.
        type: string
        minLength: 1
        maxLength: 10
      link:
        description: Resource link.
        type: string
    required:
      - version
      - link
    additionalProperties: false
    minProperties: 1
